// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-YcdVAZbywIUFMfZ2MgevA8HTB6a7s6E',
    appId: '1:88083659662:web:7deddbcb63886cc00a82df',
    messagingSenderId: '88083659662',
    projectId: 'testproject-e6131',
    authDomain: 'testproject-e6131.firebaseapp.com',
    storageBucket: 'testproject-e6131.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1J0WuijQvKr2EIbDX6QJGXmHx5pxv5Lo',
    appId: '1:88083659662:android:71714adc8d238c050a82df',
    messagingSenderId: '88083659662',
    projectId: 'testproject-e6131',
    storageBucket: 'testproject-e6131.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE-KlpXIPHGIOmQmSDpEsehHRJcLk_gkw',
    appId: '1:88083659662:ios:74287bc6d7a624590a82df',
    messagingSenderId: '88083659662',
    projectId: 'testproject-e6131',
    storageBucket: 'testproject-e6131.appspot.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE-KlpXIPHGIOmQmSDpEsehHRJcLk_gkw',
    appId: '1:88083659662:ios:ccace15f7185760d0a82df',
    messagingSenderId: '88083659662',
    projectId: 'testproject-e6131',
    storageBucket: 'testproject-e6131.appspot.com',
    iosBundleId: 'com.example.testProject.RunnerTests',
  );
}
